### ISSUE TITLE
Can we run this in a container? 

### ISSUE THREAD

**Issue by svengt** [chrislgarry/Apollo-11#39] opened 2016-07-09 21:35 UTC
🐳

**Comment by santec** [comment] 2016-07-10 00:16
Yes:

docker run -d apollo-11:latest

**Comment by peuamorim** [comment] 2016-07-10 00:36
Error:

Unable to find image 'apollo-11:latest' locally
Pulling repository docker.io/library/apollo-11
docker: Error: image library/apollo-11 not found.
See 'docker run --help'.

**Comment by venriq** [comment] 2016-07-10 01:43
Sarcasm?

**Comment by cspgx1996** [comment] 2016-07-10 01:52
Unless there's an amazing open source program that simulates rockets(written in assembly) blasting off; No...t yet

**Comment by aajahid** [comment] 2016-07-10 02:19
There is amazing program that simulates rockets - 
http://ibiblio.org/apollo/index.html

Found the domain from author email address in on of the source comment

**Comment by howditgetburned** [comment] 2016-07-10 03:54
Yes but your computer will fly away from you and into space, so run it wisely.

**Comment by aajahid** [comment] 2016-07-10 03:58
Hmm thats a problem, may be we can port SpaceX landing module - so we can get back our computer back intact? 
Btw did SpaceX released their stable build or is it still unstable?

**Comment by howditgetburned** [comment] 2016-07-10 04:02
The current most well documented workaround is to put a sack of bricks on your computer before you attempt to use the program. You can also try turning it off and turning it back on again

**Comment by cirosantilli** [comment] 2016-07-10 06:41
possible duplicate of: https://github.com/chrislgarry/Apollo-11/issues/8

**Closed** 2016-07-10 07:04 UTC
Labels: invalid

**Comment by santec** [comment] 2016-07-11 15:46
More seriously: Apollo-11 computer did not run a modern version of Linux, so no, you cannot run this program in a container.
